<?php

declare(strict_types=1);

/*
 * One schema per API resource, with the fields the resource actually
 * publishes.
 *
 * Generated once from the resource classes and maintained by hand since. The
 * guarantee that it stays true is not discipline: OpenApiSpecificationTest
 * re-reads every `toArray()` in the modules' Http\Resources directories and
 * fails the build if the field lists here and there disagree. A field added to a
 * resource without being added here is a build failure, not a documentation
 * debt.
 *
 * `additionalProperties: false` everywhere, deliberately. A permissive schema
 * would let the document stay green while the API grew fields nobody wrote
 * down.
 */

return [
    'ApiToken' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'name' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'abilities' => ['type' => 'array', 'items' => ['type' => 'string']],
            'allowed_ip_ranges' => ['type' => 'array', 'items' => ['type' => 'string']],
            'rate_limit_per_minute' => ['type' => ['integer', 'null']],
            'last_used_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'last_used_ip' => ['type' => ['string', 'null']],
            'expires_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'revoked_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'revoked_reason' => ['type' => ['string', 'null']],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'IssuedApiToken' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'The only response that ever carries a token value. The platform stores a hash and cannot show it again.',
        'properties' => [
            'token' => ['type' => 'string'],
        ],
    ],
    'Backup' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'service_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'state' => ['type' => ['string', 'null']],
            'trigger' => ['type' => ['string', 'null']],
            'mode' => ['type' => ['string', 'null']],
            'is_in_flight' => ['type' => 'boolean'],
            'is_restorable' => ['type' => 'boolean'],
            'needs_attention' => ['type' => 'boolean'],
            'size_bytes' => ['type' => ['integer', 'null']],
            'verified' => ['type' => 'boolean'],
            'verified_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'retention_days' => ['type' => ['integer', 'null']],
            'expires_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'started_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'finished_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'failure_reason' => ['type' => ['string', 'null']],
        ],
    ],
    'InvoiceItem' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'kind' => ['type' => ['string', 'null']],
            'description' => ['type' => ['string', 'null']],
            'quantity' => ['type' => ['integer', 'null']],
            'unit_amount' => ['$ref' => '#/components/schemas/Money'],
            'discount' => ['$ref' => '#/components/schemas/Money'],
            'tax' => ['$ref' => '#/components/schemas/Money'],
            'total' => ['$ref' => '#/components/schemas/Money'],
            'tax_rate' => ['type' => ['string', 'null']],
            'tax_name' => ['type' => ['string', 'null']],
            'period_start' => ['type' => ['string', 'null']],
            'period_end' => ['type' => ['string', 'null']],
        ],
    ],
    'Invoice' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'number' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'currency' => ['type' => ['string', 'null']],
            'subtotal' => ['$ref' => '#/components/schemas/Money'],
            'discount' => ['$ref' => '#/components/schemas/Money'],
            'tax' => ['$ref' => '#/components/schemas/Money'],
            'total' => ['$ref' => '#/components/schemas/Money'],
            'amount_paid' => ['$ref' => '#/components/schemas/Money'],
            'amount_refunded' => ['$ref' => '#/components/schemas/Money'],
            'amount_due' => ['$ref' => '#/components/schemas/Money'],
            'is_payable' => ['type' => 'boolean'],
            'is_settled' => ['type' => 'boolean'],
            'order_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'subscription_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'items_count' => ['type' => ['integer', 'null']],
            'items' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/InvoiceItem']],
            'issued_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'due_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'paid_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'voided_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'Subscription' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'status' => ['type' => ['string', 'null']],
            'currency' => ['type' => ['string', 'null']],
            'billing_period' => ['type' => ['string', 'null']],
            'recurring_amount' => ['$ref' => '#/components/schemas/Money'],
            'plan_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'order_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'current_period_start' => ['type' => ['string', 'null']],
            'current_period_end' => ['type' => ['string', 'null']],
            'next_invoice_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'auto_renew' => ['type' => 'boolean'],
            'cancel_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'cancelled_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'ended_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'grace_period_ends_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'is_scheduled_to_cancel' => ['type' => 'boolean'],
            'service_is_running' => ['type' => ['string', 'null']],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'PlanPrice' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'billing_period' => ['type' => ['string', 'null']],
            'currency' => ['type' => ['string', 'null']],
            'recurring' => ['$ref' => '#/components/schemas/Money'],
            'setup' => ['$ref' => '#/components/schemas/Money'],
        ],
    ],
    'Plan' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'product_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'slug' => ['type' => ['string', 'null']],
            'name' => ['type' => ['string', 'null']],
            'description' => ['type' => ['string', 'null']],
            'resources' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'stock_limit' => ['type' => ['integer', 'null']],
            'per_customer_limit' => ['type' => ['integer', 'null']],
            'prices' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/PlanPrice']],
            'product' => ['type' => ['object', 'null'], 'additionalProperties' => true],
        ],
    ],
    'Product' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'kind' => ['type' => ['string', 'null']],
            'slug' => ['type' => ['string', 'null']],
            'name' => ['type' => ['string', 'null']],
            'description' => ['type' => ['string', 'null']],
            'plan_count' => ['type' => ['integer', 'null']],
            'plans' => ['type' => 'array', 'items' => ['type' => 'object', 'additionalProperties' => true]],
        ],
    ],
    'DedicatedServer' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'serial' => ['type' => ['string', 'null']],
            'manufacturer' => ['type' => ['string', 'null']],
            'model' => ['type' => ['string', 'null']],
            'hardware_profile' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'status' => ['type' => ['string', 'null']],
            'power_state' => ['type' => ['string', 'null']],
            'is_powered_on' => ['type' => 'boolean'],
            'service_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'activated_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'components' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/ServerComponent']],
        ],
    ],
    'ReinstallRequest' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'state' => ['type' => ['string', 'null']],
            'is_settled' => ['type' => 'boolean'],
            'requested_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'started_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'finished_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'ServerComponent' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'kind' => ['type' => ['string', 'null']],
            'model' => ['type' => ['string', 'null']],
            'quantity' => ['type' => ['integer', 'null']],
            'health' => ['type' => ['string', 'null']],
            'needs_attention' => ['type' => 'boolean'],
        ],
    ],
    'Customer' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'type' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'display_name' => ['type' => ['string', 'null']],
            'legal_name' => ['type' => ['string', 'null']],
            'currency' => ['type' => ['string', 'null']],
            'country' => ['type' => ['string', 'null']],
            'can_purchase' => ['type' => 'boolean'],
            'role' => ['type' => ['string', 'null']],
        ],
    ],
    'User' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'name' => ['type' => ['string', 'null']],
            'email' => ['type' => ['string', 'null']],
            'email_verified' => ['type' => 'boolean'],
            'locale' => ['type' => ['string', 'null']],
            'timezone' => ['type' => ['string', 'null']],
            'phone' => ['type' => ['string', 'null']],
            'two_factor_enabled' => ['type' => 'boolean'],
            'last_login_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'permissions' => ['type' => 'array', 'items' => ['type' => 'string']],
            'customers' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/Customer']],
        ],
    ],
    'IpAssignment' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'ip_address' => ['type' => ['string', 'null']],
            'ip_version' => ['type' => ['integer', 'null']],
            'is_primary' => ['type' => 'boolean'],
            'mac_address' => ['type' => ['string', 'null']],
            'service_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'assigned_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'network' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'gateway' => ['type' => ['string', 'null']],
            'prefix_length' => ['type' => ['integer', 'null']],
            'reverse_dns' => ['type' => ['string', 'null']],
        ],
    ],
    'ReverseDnsRecord' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'hostname' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'is_settled' => ['type' => 'boolean'],
            'updated_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'OrderItem' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'kind' => ['type' => ['string', 'null']],
            'name' => ['type' => ['string', 'null']],
            'billing_period' => ['type' => ['string', 'null']],
            'quantity' => ['type' => ['integer', 'null']],
            'plan_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'resources' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'unit_recurring' => ['$ref' => '#/components/schemas/Money'],
            'unit_setup' => ['$ref' => '#/components/schemas/Money'],
            'discount' => ['$ref' => '#/components/schemas/Money'],
            'tax' => ['$ref' => '#/components/schemas/Money'],
            'total' => ['$ref' => '#/components/schemas/Money'],
            'tax_rate' => ['type' => ['string', 'null']],
            'tax_name' => ['type' => ['string', 'null']],
        ],
    ],
    'Order' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'number' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'currency' => ['type' => ['string', 'null']],
            'subtotal' => ['$ref' => '#/components/schemas/Money'],
            'discount' => ['$ref' => '#/components/schemas/Money'],
            'tax' => ['$ref' => '#/components/schemas/Money'],
            'total' => ['$ref' => '#/components/schemas/Money'],
            'notes' => ['type' => ['string', 'null']],
            'is_paid' => ['type' => 'boolean'],
            'is_cancellable' => ['type' => 'boolean'],
            'coupon_code' => ['type' => ['string', 'null']],
            'items_count' => ['type' => ['integer', 'null']],
            'items' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/OrderItem']],
            'placed_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'paid_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'completed_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'cancelled_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'Payment' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'kind' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'amount' => ['$ref' => '#/components/schemas/Money'],
            'invoice_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'provider' => ['type' => ['string', 'null']],
            'is_settled' => ['type' => 'boolean'],
            'failure_code' => ['type' => ['string', 'null']],
            'failure_message' => ['type' => ['string', 'null']],
            'processed_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'StartedPayment' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'payment' => ['type' => ['string', 'null']],
            'provider' => ['type' => ['string', 'null']],
            'reference' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'next_action' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'type' => ['type' => ['string', 'null']],
            'redirect_url' => ['type' => ['string', 'null']],
            'client_secret' => ['type' => ['string', 'null']],
            'failure_code' => ['type' => ['string', 'null']],
            'failure_message' => ['type' => ['string', 'null']],
        ],
    ],
    'ProvisioningEvent' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'kind' => ['type' => ['string', 'null']],
            'state' => ['type' => ['string', 'null']],
            'is_settled' => ['type' => 'boolean'],
            'failure_reason' => ['type' => ['string', 'null']],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'started_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'finished_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'Service' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'kind' => ['type' => ['string', 'null']],
            'label' => ['type' => ['string', 'null']],
            'state' => ['type' => ['string', 'null']],
            'is_usable' => ['type' => 'boolean'],
            'resources' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'plan_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'order_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'order_item_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'subscription_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'activated_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'suspended_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'terminated_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'HostingAccount' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'service_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'username' => ['type' => ['string', 'null']],
            'primary_domain' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'package' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'slug' => ['type' => ['string', 'null']],
            'disk_quota_mib' => ['type' => ['integer', 'null']],
            'bandwidth_quota_mib' => ['type' => ['integer', 'null']],
            'max_addon_domains' => ['type' => ['integer', 'null']],
            'max_subdomains' => ['type' => ['integer', 'null']],
            'max_databases' => ['type' => ['integer', 'null']],
            'max_email_accounts' => ['type' => ['integer', 'null']],
            'ssl' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'expires_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'suspended_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'suspension_reason' => ['type' => ['string', 'null']],
            'retention_releases_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'terminated_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'HostingAccountUsage' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'account_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'username' => ['type' => ['string', 'null']],
            'disk' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'bandwidth' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'measured_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'HostingPanelSession' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'url' => ['type' => ['string', 'null']],
            'username' => ['type' => ['string', 'null']],
            'expires_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'expires_in' => ['type' => ['integer', 'null']],
            'single_use' => ['type' => 'boolean'],
        ],
    ],
    'ConsoleSession' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'virtual_machine_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'token' => ['type' => ['string', 'null']],
            'gateway' => ['type' => ['string', 'null']],
            'expires_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'expires_in' => ['type' => ['integer', 'null']],
            'single_use' => ['type' => 'boolean'],
            'ttl_seconds' => ['type' => ['integer', 'null']],
        ],
    ],
    'ProvisioningOperation' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'service_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'kind' => ['type' => ['string', 'null']],
            'action' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'is_settled' => ['type' => 'boolean'],
            'needs_attention' => ['type' => 'boolean'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'finished_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'VirtualMachine' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'service_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'hostname' => ['type' => ['string', 'null']],
            'service_status' => ['type' => ['string', 'null']],
            'power_state' => ['type' => ['string', 'null']],
            'resources' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'vcpu' => ['type' => ['integer', 'null']],
            'memory_mib' => ['type' => ['integer', 'null']],
            'disk_gib' => ['type' => ['integer', 'null']],
            'os_family' => ['type' => ['string', 'null']],
            'os_version' => ['type' => ['string', 'null']],
            'addresses' => ['type' => 'array', 'items' => ['type' => 'object', 'additionalProperties' => true]],
            'is_operable' => ['type' => 'boolean'],
            /*
             * The machine's most recent rebuild, or null if it has never had
             * one. `data_destroyed` is the field a client should read before
             * offering a customer any recovery advice: it is true from the
             * moment the disk replacement was attempted, including when the
             * platform does not know whether it happened.
             */
            'reinstall' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            // The fields inside it, listed flat in the same way the machine's
            // `resources` block is: the parity check between these schemas and
            // the resources compares one level, and a nested block that
            // documented its own keys would read as undocumented.
            'state' => ['type' => ['string', 'null']],
            'in_flight' => ['type' => ['boolean', 'null']],
            'needs_attention' => ['type' => ['boolean', 'null']],
            'data_destroyed' => ['type' => ['boolean', 'null']],
            'requested_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'completed_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'WalletBalance' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'wallet_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'currency' => ['type' => ['string', 'null']],
            'balance' => ['$ref' => '#/components/schemas/Money'],
            'updated_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'WalletTransaction' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'wallet_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'kind' => ['type' => ['string', 'null']],
            'amount' => ['$ref' => '#/components/schemas/Money'],
            'direction' => ['type' => ['string', 'null']],
            'balance_after' => ['$ref' => '#/components/schemas/Money'],
            'description' => ['type' => ['string', 'null']],
            'invoice_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'transaction_id' => ['oneOf' => [['$ref' => '#/components/schemas/Ulid'], ['type' => 'null']]],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],

    /*
     * The account surface's own shapes, which are not Resource classes: the
     * two-factor and session endpoints return small purpose-built payloads.
     */
    'Session' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'ip_address' => ['type' => ['string', 'null']],
            'user_agent' => ['type' => ['string', 'null']],
            'is_current' => ['type' => 'boolean'],
            'last_active_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'LoginActivity' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'successful' => ['type' => 'boolean'],
            'ip_address' => ['type' => ['string', 'null']],
            'user_agent' => ['type' => ['string', 'null']],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'TwoFactorSetup' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'The shared secret and its otpauth URI. Not enabled until confirmed.',
        'properties' => [
            'secret' => ['type' => 'string'],
            'otpauth_uri' => ['type' => 'string'],
        ],
    ],
    'RecoveryCodes' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'Shown once. The platform stores hashes and cannot show them again.',
        'properties' => [
            'recovery_codes' => ['type' => 'array', 'items' => ['type' => 'string']],
        ],
    ],

    /*
     * The operator surface builds its payloads in the controllers rather than
     * in Resource classes, because what an operator needs is a different shape
     * from what a customer needs — and because each of these deliberately
     * omits something: an api_endpoint, a credentials reference, a provider's
     * raw payload.
     */
    'AdminCustomer' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'type' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'display_name' => ['type' => ['string', 'null']],
            'legal_name' => ['type' => ['string', 'null']],
            'billing_email' => ['type' => ['string', 'null']],
            'currency' => ['type' => ['string', 'null']],
            'country' => ['type' => ['string', 'null']],
            'services_count' => ['type' => ['integer', 'null']],
            'invoices_count' => ['type' => ['integer', 'null']],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'AdminProvisioningJob' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'kind' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'provider' => ['type' => ['string', 'null']],
            'customer_id' => ['type' => ['string', 'null']],
            'service_id' => ['type' => ['string', 'null']],
            'attempts' => ['type' => ['integer', 'null']],
            'max_attempts' => ['type' => ['integer', 'null']],
            'failure_class' => ['type' => ['string', 'null']],
            'last_error' => ['type' => ['string', 'null']],
            'correlation_id' => ['type' => ['string', 'null']],
            'started_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'finished_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'next_attempt_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'AdminNode' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'name' => ['type' => ['string', 'null']],
            'cluster' => ['type' => ['string', 'null']],
            'datacenter' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'is_healthy' => ['type' => 'boolean'],
            'vm_count' => ['type' => ['integer', 'null']],
            'cpu' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'memory_mib' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'storage_gib' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'last_seen_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'AdminIpPool' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'slug' => ['type' => ['string', 'null']],
            'name' => ['type' => ['string', 'null']],
            'ip_version' => ['type' => ['integer', 'null']],
            'scope' => ['type' => ['string', 'null']],
            'datacenter' => ['type' => ['string', 'null']],
            'subnets_count' => ['type' => ['integer', 'null']],
            'quarantine_days' => ['type' => ['integer', 'null']],
            'is_active' => ['type' => 'boolean'],
        ],
    ],
    'AdminDedicatedServer' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'serial' => ['type' => ['string', 'null']],
            'asset_tag' => ['type' => ['string', 'null']],
            'manufacturer' => ['type' => ['string', 'null']],
            'model' => ['type' => ['string', 'null']],
            'hardware_profile' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'power_state' => ['type' => ['string', 'null']],
            'customer_id' => ['type' => ['string', 'null']],
            'service_id' => ['type' => ['string', 'null']],
            'rack_unit' => ['type' => ['string', 'null']],
        ],
    ],
    'AdminHostingNode' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'Names no api_endpoint and no credentials reference. An operator screen has no use for either, and a support tool that displays them puts them in a screenshot.',
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'slug' => ['type' => ['string', 'null']],
            'hostname' => ['type' => ['string', 'null']],
            'panel' => ['type' => ['string', 'null']],
            'panel_version' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'accepts_new_accounts' => ['type' => 'boolean'],
            'panel_licensed' => ['type' => 'boolean'],
            'licence_status' => ['type' => ['string', 'null']],
            'account_count' => ['type' => ['integer', 'null']],
            'max_accounts' => ['type' => ['integer', 'null']],
            'disk_used_mib' => ['type' => ['integer', 'null']],
            'disk_total_mib' => ['type' => ['integer', 'null']],
            'load_average' => ['type' => ['string', 'null']],
            'last_synced_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'AdminDrift' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'One disagreement between the platform and a provider. `expected` and `observed` are redacted on write by the model cast, not here.',
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'provider' => ['type' => ['string', 'null']],
            'resource_type' => ['type' => ['string', 'null']],
            'service_id' => ['type' => ['string', 'null']],
            'provider_reference' => ['type' => ['string', 'null']],
            'kind' => ['type' => ['string', 'null']],
            'severity' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'expected' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'observed' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'occurrences' => ['type' => ['integer', 'null']],
            'first_seen_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'last_seen_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'resolution' => ['type' => ['string', 'null']],
            'resolved_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'Notification' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'One thing the platform told this customer. Title and body are rendered per request in the caller\'s language: the row stores facts, not prose, so a customer who switches to Arabic sees their whole history in Arabic.',
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'type' => ['type' => ['string', 'null']],
            'category' => ['type' => ['string', 'null'], 'description' => 'security and billing cannot be silenced; service and operational can be, by email only.'],
            'title' => ['type' => ['string', 'null']],
            'body' => ['type' => ['string', 'null']],
            'is_failure' => ['type' => 'boolean'],
            'link' => ['type' => ['string', 'null'], 'description' => 'A portal path, not a URL, so it stays correct when the host changes.'],
            'read_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'NotificationPreference' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'One category on one channel. `changeable` is false where the platform will not honour a change - security and billing carry obligations and warnings, and the in-app inbox is the account\'s own record of what happened to it.',
        'properties' => [
            'category' => ['type' => 'string'],
            'channel' => ['type' => 'string'],
            'enabled' => ['type' => 'boolean'],
            'changeable' => ['type' => 'boolean'],
        ],
    ],
    'NotificationsMarkedRead' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'marked_read' => ['type' => 'integer'],
            'unread' => ['type' => 'integer'],
        ],
    ],
    'AdminHostingAccountState' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'status' => ['type' => ['string', 'null']],
        ],
    ],
    'PlanChange' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'Both halves of the proration, not only the net: a customer owed a credit and charged a larger amount should see both numbers rather than one they cannot check.',
        'properties' => [
            'subscription' => ['$ref' => '#/components/schemas/Subscription'],
            'credit' => ['$ref' => '#/components/schemas/Money'],
            'charge' => ['$ref' => '#/components/schemas/Money'],
            'net' => ['$ref' => '#/components/schemas/Money'],
            'effective_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'period_end' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'AdminAdoptedJob' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'status' => ['type' => ['string', 'null']],
            'service_id' => ['type' => ['string', 'null']],
        ],
    ],
    'AdminReconciliationRequest' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'cluster_id' => ['$ref' => '#/components/schemas/Ulid'],
            'queued' => ['type' => 'boolean'],
        ],
    ],
    'AdminVoidedInvoice' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'number' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
        ],
    ],
    'AuditEntry' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'One irreversible act. Append-only: there is no endpoint that can amend or delete an entry.',
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'action' => ['type' => ['string', 'null']],
            'actor_type' => ['type' => ['string', 'null']],
            'actor_id' => ['type' => ['string', 'null']],
            'actor_label' => ['type' => ['string', 'null'], 'description' => 'The operator as they were at the time, so the trail does not change when somebody is renamed.'],
            'subject_type' => ['type' => ['string', 'null']],
            'subject_id' => ['type' => ['string', 'null']],
            'customer_id' => ['type' => ['string', 'null']],
            'context' => ['type' => ['object', 'null'], 'additionalProperties' => true],
            'ip_address' => ['type' => ['string', 'null']],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'AdminInvoice' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'number' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'customer_id' => ['type' => ['string', 'null']],
            'currency' => ['type' => ['string', 'null']],
            'total' => ['$ref' => '#/components/schemas/Money'],
            'amount_paid' => ['$ref' => '#/components/schemas/Money'],
            'amount_due' => ['$ref' => '#/components/schemas/Money'],
            'issued_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'due_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'paid_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'AdminTransaction' => [
        'type' => 'object',
        'additionalProperties' => false,
        'description' => 'Names no provider_metadata. A provider payload is where a credential eventually appears.',
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'kind' => ['type' => ['string', 'null']],
            'status' => ['type' => ['string', 'null']],
            'provider' => ['type' => ['string', 'null']],
            'amount' => ['$ref' => '#/components/schemas/Money'],
            'invoice_id' => ['type' => ['string', 'null']],
            'customer_id' => ['type' => ['string', 'null']],
            'processed_at' => ['$ref' => '#/components/schemas/Timestamp'],
            'created_at' => ['$ref' => '#/components/schemas/Timestamp'],
        ],
    ],
    'AdminRefund' => [
        'type' => 'object',
        'additionalProperties' => false,
        'properties' => [
            'id' => ['$ref' => '#/components/schemas/Ulid'],
            'transaction_id' => ['type' => ['string', 'null']],
            'amount' => ['$ref' => '#/components/schemas/Money'],
            'status' => ['type' => ['string', 'null']],
        ],
    ],
];
