<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Routing\Route as RoutingRoute;
use Illuminate\Support\Facades\Route;
use Lynomia\Support\YamlEmitter;
use RuntimeException;

/**
 * Writes docs/openapi.yaml from the routes the application actually registers.
 *
 * The structure — which paths exist, which methods, which path parameters,
 * whether a route is authenticated, which permission an operator route needs —
 * is read from the route table rather than typed, because a hand-maintained
 * list of endpoints diverges from the application the first week nobody
 * remembers to update it.
 *
 * The meaning — what an endpoint is for, what its body looks like, why a 409
 * means what it means — is hand-written in resources/openapi/operations.php,
 * because none of it is derivable from a route table.
 *
 * The command refuses to write a document while any registered route has no
 * entry, and while any entry names a route that does not exist. That is the
 * gate: an endpoint cannot be added without being documented, and the document
 * cannot describe an endpoint the platform does not serve.
 */
final class GenerateOpenApiSpec extends Command
{
    protected $signature = 'openapi:generate {--check : Fail if the committed file is out of date, and write nothing}';

    protected $description = 'Generate the OpenAPI 3.1 description of this API from the route table';

    private const string OUTPUT = 'docs/openapi.yaml';

    public function handle(): int
    {
        $operations = require base_path('resources/openapi/operations.php');
        $components = require base_path('resources/openapi/components.php');
        $schemas = require base_path('resources/openapi/schemas.php');

        $routes = self::describableRoutes();

        if (($problem = self::disagreement($routes, $operations)) !== null) {
            $this->error($problem);

            return self::FAILURE;
        }

        $document = self::document($routes, $operations, $components, $schemas);
        $yaml = "# Generated by `php artisan openapi:generate`. Do not edit by hand.\n"
            ."# The meaning lives in resources/openapi/; this file is its serialisation.\n"
            .YamlEmitter::emit($document);

        $path = base_path('../../'.self::OUTPUT);

        if ($this->option('check')) {
            $current = is_file($path) ? file_get_contents($path) : '';

            if ($current !== $yaml) {
                $this->error(self::OUTPUT.' is out of date. Run `php artisan openapi:generate`.');

                return self::FAILURE;
            }

            $this->info(self::OUTPUT.' is up to date: '.count($routes).' operations.');

            return self::SUCCESS;
        }

        file_put_contents($path, $yaml);
        $this->info('Wrote '.self::OUTPUT.': '.count($routes).' operations.');

        return self::SUCCESS;
    }

    /**
     * Every route this document is expected to describe.
     *
     * The API and the webhook endpoint. Nothing else is registered — there are
     * no HTML routes on this application — but the filter is explicit so that
     * adding one does not silently enlarge the document.
     *
     * @return array<string, RoutingRoute> keyed by route name
     */
    public static function describableRoutes(): array
    {
        $routes = [];

        /*
         * getRoutes() is typed as the collection interface, which is not
         * declared iterable even though the implementation is. Taking the
         * array is both honest about that and stable.
         */
        foreach (Route::getRoutes()->getRoutes() as $route) {
            $uri = $route->uri();

            if (! str_starts_with($uri, 'api/') && ! str_starts_with($uri, 'webhooks/')) {
                continue;
            }

            $name = $route->getName();

            if ($name === null) {
                throw new RuntimeException(sprintf(
                    'The route %s has no name, so it cannot be documented. Name it.',
                    $uri,
                ));
            }

            $routes[$name] = $route;
        }

        ksort($routes);

        return $routes;
    }

    /**
     * @param  array<string, RoutingRoute>  $routes
     * @param  array<string, mixed>  $operations
     */
    private static function disagreement(array $routes, array $operations): ?string
    {
        $undocumented = array_diff(array_keys($routes), array_keys($operations));

        if ($undocumented !== []) {
            return sprintf(
                "These routes are registered and not documented in resources/openapi/operations.php:\n  %s",
                implode("\n  ", $undocumented),
            );
        }

        $imaginary = array_diff(array_keys($operations), array_keys($routes));

        if ($imaginary !== []) {
            return sprintf(
                "These operations describe routes the application does not register:\n  %s",
                implode("\n  ", $imaginary),
            );
        }

        return null;
    }

    /**
     * @param  array<string, RoutingRoute>  $routes
     * @param  array<string, mixed>  $operations
     * @param  array<string, mixed>  $components
     * @param  array<string, mixed>  $schemas
     * @return array<string, mixed>
     */
    private static function document(array $routes, array $operations, array $components, array $schemas): array
    {
        $paths = [];

        foreach ($routes as $name => $route) {
            /** @var array<string, mixed> $operation */
            $operation = $operations[$name];

            $path = '/'.$route->uri();

            foreach ($route->methods() as $method) {
                if (in_array($method, ['HEAD', 'OPTIONS'], true)) {
                    continue;
                }

                $paths[$path][strtolower($method)] = self::operation($name, $route, $operation);
            }
        }

        ksort($paths);

        /** @var callable(string): array<string, mixed> $page */
        $page = $components['page'];
        /** @var callable(string): array<string, mixed> $single */
        $single = $components['single'];

        $allSchemas = $components['schemas'];

        /*
         * Only the envelope variants something references. Emitting a Page and
         * a Response for every resource whether or not either is used fills the
         * document with components nobody can reach — which a validator
         * reports, correctly, as dead weight in a public contract.
         */
        $referenced = self::referencedSchemas($paths);

        foreach ($schemas as $schemaName => $schema) {
            $allSchemas[$schemaName] = $schema;

            if (isset($referenced[$schemaName.'Page'])) {
                $allSchemas[$schemaName.'Page'] = $page($schemaName);
            }

            if (isset($referenced[$schemaName.'Response'])) {
                $allSchemas[$schemaName.'Response'] = $single($schemaName);
            }
        }

        ksort($allSchemas);

        return [
            'openapi' => '3.1.0',
            'info' => self::apiInfo(),
            'servers' => [
                ['url' => '{origin}', 'description' => 'The deployment you are talking to.', 'variables' => [
                    'origin' => ['default' => 'https://cloud.lynomia.test', 'description' => 'Scheme and host of the control plane.'],
                ]],
            ],
            'tags' => self::tags($operations),
            'security' => [
                ['sessionCookie' => []],
                ['personalAccessToken' => []],
            ],
            'paths' => $paths,
            'components' => [
                'securitySchemes' => $components['securitySchemes'],
                'parameters' => $components['parameters'],
                'headers' => $components['headers'],
                'schemas' => $allSchemas,
            ],
        ];
    }

    /**
     * Every `#/components/schemas/X` the paths object mentions.
     *
     * @param  array<string, mixed>  $paths
     * @return array<string, true>
     */
    private static function referencedSchemas(array $paths): array
    {
        // UNESCAPED_SLASHES matters: json_encode writes "#\/components\/..."
        // by default, and a pattern looking for the unescaped form silently
        // matches nothing — which prunes every envelope the document uses.
        $json = json_encode($paths, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);

        preg_match_all('#\#/components/schemas/([A-Za-z0-9_]+)#', $json, $matches);

        return array_fill_keys($matches[1], true);
    }

    /**
     * @return array<string, mixed>
     */
    private static function apiInfo(): array
    {
        return [
            'title' => 'Lynomia Cloud API',
            'version' => '1.0.0',
            'summary' => 'Cloud VPS, dedicated servers and shared hosting, with their billing.',
            'description' => <<<'TEXT'
            This document is generated from the route table of the running
            application. It cannot describe an endpoint that does not exist,
            and the build fails if an endpoint exists that it does not describe.

            ## What every response looks like

            A single resource comes back as `{"data": {…}}`. A collection comes
            back as `{"data": […], "meta": {…}}` with the same paging envelope
            everywhere. A failure comes back as `{"error": {"code", "message",
            …}}` — branch on the code, never on the status or the prose.

            ## Money

            Integer minor units and a currency, never a float. The `amount`
            string is for display and must not be parsed back into arithmetic.

            ## Which account a request acts on

            A principal may belong to several billing accounts. Send
            `X-Customer-Id` to choose; omit it if you belong to one. A token
            already scoped to an account wins over the header. Membership is
            re-checked on every request.

            ## Retries

            Anything that reaches a provider — placing an order, taking a
            backup, changing power — should carry an `Idempotency-Key`. A
            timeout on this API means the platform stopped waiting, not that
            the provider stopped working: retrying without a key is how a
            customer ends up with two machines, or two charges.

            ## Rate limits

            Every authenticated route is limited, and the operations that cost
            real money or real hardware are limited far below the general
            ceiling. A 429 carries `Retry-After`.

            ## Not described here

            There is no support-ticket API, no DNS zone management API and no
            restore or delete for backups. Each is absent because it is not
            implemented, not because it is undocumented — see
            docs/build-status.md.
            TEXT,
            'license' => ['name' => 'Proprietary', 'identifier' => 'LicenseRef-Proprietary'],
        ];
    }

    /**
     * @param  array<string, mixed>  $operations
     * @return list<array<string, string>>
     */
    private static function tags(array $operations): array
    {
        $tags = [];

        foreach ($operations as $operation) {
            $tag = is_array($operation) ? (string) ($operation['tag'] ?? 'Other') : 'Other';
            $tags[$tag] = true;
        }

        $names = array_keys($tags);
        sort($names);

        // Every tag says what it is for. A generated document with fourteen
        // bare tag names is a navigation menu with no labels.
        $descriptions = [
            'Account' => 'The signed-in person: their profile, their password, their second factor and the devices they are signed in on.',
            'API tokens' => 'Credentials for integrations. Shown once at creation; the platform stores a hash.',
            'Authentication' => 'Signing in and out, verifying an address, resetting a password. Rate-limited harder than anything else here.',
            'Backups' => 'Backups of a machine. A state moves to succeeded only when the provider says the task finished, never because a job was accepted.',
            'Billing' => 'Invoices, subscriptions, payments and the wallet. Money is integer minor units throughout.',
            'Catalogue' => 'What is for sale, priced in the account\'s currency.',
            'Cloud VPS' => 'Virtual machines: their state, their power, their console and their reinstalls.',
            'Dedicated servers' => 'Physical machines, controlled through a BMC the API never exposes.',
            'IP addresses' => 'Addresses assigned to the account, and their reverse DNS.',
            'Notifications' => 'What the platform has told this customer, and what they have read. Security and billing messages cannot be switched off.',
            'Operator' => 'The NOC surface. Same guard as the customer API — what separates them is that every route here names the permission it needs.',
            'Orders' => 'Placing and cancelling orders. Nothing is provisioned until a payment has been verified server-side.',
            'Services' => 'What the account owns, whatever kind it is, and what the platform has done to it.',
            'Support' => 'Tickets between an account and the support team. A customer may open, reply and close; resolving is the team\'s judgement and is not on this surface. Internal notes never appear here at all.',
            'Shared hosting' => 'Panel accounts, their usage, and single-use sign-in links to the panel.',
            'Team' => 'Who belongs to this account and what each of them may do. The three /invitations routes are the invitee\'s side, and are the only customer routes that work for somebody who belongs to no account yet.',
            'Webhooks' => 'Called by providers, not by clients. Signature-verified before the body is parsed.',
        ];

        return array_map(
            static fn (string $name): array => array_filter([
                'name' => $name,
                'description' => $descriptions[$name] ?? null,
            ], static fn (mixed $value): bool => $value !== null),
            $names,
        );
    }

    /**
     * @param  array<string, mixed>  $operation
     * @return array<string, mixed>
     */
    private static function operation(string $name, RoutingRoute $route, array $operation): array
    {
        $out = [
            'operationId' => str_replace('.', '_', $name),
            'tags' => [(string) ($operation['tag'] ?? 'Other')],
            'summary' => (string) ($operation['summary'] ?? ''),
        ];

        if (isset($operation['description'])) {
            $out['description'] = (string) $operation['description'];
        }

        if (($permission = $operation['permission'] ?? null) !== null) {
            $out['description'] = trim(($out['description'] ?? '')."\n\nRequires the `".$permission.'` permission.');
        }

        $parameters = self::parameters($route, $operation);

        if ($parameters !== []) {
            $out['parameters'] = $parameters;
        }

        if (isset($operation['body'])) {
            $out['requestBody'] = self::requestBody($operation);
        }

        $out['security'] = ($operation['auth'] ?? true) === false
            ? []
            : [['sessionCookie' => []], ['personalAccessToken' => []]];

        $out['responses'] = self::responses($operation);

        return $out;
    }

    /**
     * @param  array<string, mixed>  $operation
     * @return list<array<string, mixed>>
     */
    private static function parameters(RoutingRoute $route, array $operation): array
    {
        $parameters = [];

        foreach ($route->parameterNames() as $parameter) {
            $parameters[] = [
                'name' => $parameter,
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'string'],
            ];
        }

        $envelope = is_array($operation['response'] ?? null) ? ($operation['response']['envelope'] ?? null) : null;

        if ($envelope === 'page') {
            $parameters[] = ['$ref' => '#/components/parameters/page'];
            $parameters[] = ['$ref' => '#/components/parameters/perPage'];
        }

        /** @var list<string> $query */
        $query = $operation['query'] ?? [];

        foreach ($query as $field) {
            $parameters[] = [
                'name' => $field,
                'in' => 'query',
                'required' => false,
                'schema' => ['type' => 'string'],
            ];
        }

        if (($operation['auth'] ?? true) !== false) {
            $parameters[] = ['$ref' => '#/components/parameters/customerId'];
        }

        $method = in_array('POST', $route->methods(), true) || in_array('PUT', $route->methods(), true);

        if ($method && ($operation['auth'] ?? true) !== false) {
            $parameters[] = ['$ref' => '#/components/parameters/idempotencyKey'];
        }

        return $parameters;
    }

    /**
     * @param  array<string, mixed>  $operation
     * @return array<string, mixed>
     */
    private static function requestBody(array $operation): array
    {
        /** @var list<string> $fields */
        $fields = $operation['body'];

        $properties = [];

        foreach ($fields as $field) {
            $properties[$field] = ['description' => 'See the endpoint description; validated server-side.'];
        }

        return [
            'required' => true,
            'content' => [
                'application/json' => [
                    'schema' => [
                        'type' => 'object',
                        'properties' => $properties,
                    ],
                ],
            ],
        ];
    }

    /**
     * @param  array<string, mixed>  $operation
     * @return array<int|string, mixed>
     */
    private static function responses(array $operation): array
    {
        /** @var array<string, mixed> $response */
        $response = $operation['response'] ?? ['envelope' => 'none', 'status' => 204];

        $status = (string) ($response['status'] ?? 200);
        $envelope = (string) ($response['envelope'] ?? 'none');
        $schema = isset($response['schema']) ? (string) $response['schema'] : null;

        $success = match ($envelope) {
            'page' => ['description' => 'A page of results.', 'content' => self::json($schema.'Page')],
            'single' => ['description' => 'The resource.', 'content' => self::json($schema.'Response')],
            'list' => ['description' => 'Every result, unpaged.', 'content' => [
                'application/json' => ['schema' => [
                    'type' => 'object',
                    'required' => ['data'],
                    'properties' => ['data' => [
                        'type' => 'array',
                        'items' => ['$ref' => '#/components/schemas/'.$schema],
                    ]],
                ]],
            ]],
            'redirect' => ['description' => 'A redirect back to the portal.'],
            default => ['description' => 'No content.'],
        };

        // Both headers are on every response the application sends: the
        // correlation id from global middleware, the remaining allowance from
        // the throttler. Documenting them is what lets a client log the first
        // and back off on the second.
        $success['headers'] = [
            'X-Request-Id' => ['$ref' => '#/components/headers/RequestId'],
            'X-RateLimit-Remaining' => ['$ref' => '#/components/headers/RateLimitRemaining'],
        ];

        $responses = [$status => $success];

        if (($operation['auth'] ?? true) !== false) {
            $responses['401'] = self::errorResponse('Not authenticated. `auth.unauthenticated`.');
            $responses['403'] = self::errorResponse('Not permitted. `auth.forbidden`, whatever the underlying refusal was.');
        }

        if (isset($operation['body'])) {
            $responses['422'] = self::errorResponse('The body did not validate. `validation.failed`, with the failing fields in `error.details`.');
        }

        $responses['404'] = self::errorResponse(
            'Not found. An identifier belonging to another account answers this rather than 403: a 403 confirms the id exists, which over a loop is an inventory of the platform.',
        );

        $responses['429'] = [
            'description' => 'Rate limited. `Retry-After` says how long to wait.',
            'headers' => ['Retry-After' => ['$ref' => '#/components/headers/RetryAfter']],
            'content' => self::json('Error'),
        ];

        return $responses;
    }

    /**
     * @return array<string, mixed>
     */
    private static function errorResponse(string $description): array
    {
        return ['description' => $description, 'content' => self::json('Error')];
    }

    /**
     * @return array<string, mixed>
     */
    private static function json(string $schema): array
    {
        return ['application/json' => ['schema' => ['$ref' => '#/components/schemas/'.$schema]]];
    }
}
