<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | The documents a customer accepts at registration
    |--------------------------------------------------------------------------
    |
    | Where the terms of service and the acceptable use policy are published.
    | Both start unset, and that is not an oversight: the documents themselves
    | are a business and legal deliverable, written and reviewed by people
    | rather than generated by this repository, and a URL here that pointed at
    | a page nobody had written would be worse than no URL at all.
    |
    | The software's half is done and is what these keys are: the registration
    | form asks for acceptance, the API requires it, and the acceptance is
    | recorded against the account. When the documents exist, publishing them
    | is setting these two variables — the registration screen then links the
    | words a customer is being asked to accept, and no business code changes.
    |
    | Until then the screen names the documents without linking them, which is
    | exactly what "the documents do not exist yet" looks like, and is recorded
    | as a launch prerequisite rather than hidden behind a placeholder page.
    |
    */

    'terms_url' => env('LEGAL_TERMS_URL'),

    'aup_url' => env('LEGAL_AUP_URL'),

];
