<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | The documents a customer accepts at registration
    |--------------------------------------------------------------------------
    |
    | Where the terms of service and the acceptable use policy are published,
    | and which revision of each is current. All four start unset, and that is
    | not an oversight: the documents themselves are a business and legal
    | deliverable, written and reviewed by people rather than generated by this
    | repository, and a URL here that pointed at a page nobody had written
    | would be worse than no URL at all.
    |
    | Unset means registration is refused. That is the part this repository got
    | wrong for a long time and has now fixed. The screen asked for acceptance,
    | the API required the box to be ticked, and a comment here claimed the
    | acceptance "is recorded against the account" — while `accepts_terms`
    | appeared in exactly one place in the codebase, a validation rule, and was
    | discarded the moment it passed. So an account could be created on the
    | strength of a customer agreeing to two document names that linked
    | nowhere, and the platform kept no record of it having happened.
    |
    | Now: no published documents, no registration. An unwritten policy is not
    | a lenient policy, and a launch prerequisite that quietly lets customers
    | in is not a prerequisite.
    |
    | A version is required alongside each URL because an acceptance has to
    | name what was accepted. "This customer accepted the terms" is not a fact
    | anyone can act on once the terms have been rewritten twice. The value is
    | a stable identifier rather than a title — `2026-04-01`, `1.4`, `v3` — and
    | it is read from here on the server every time. It is never accepted from
    | the browser: a client that could name the version it was agreeing to
    | could name last year's.
    |
    | Publishing is setting these four values. No business code changes.
    |
    */

    'terms_url' => env('LEGAL_TERMS_URL'),

    'terms_version' => env('LEGAL_TERMS_VERSION'),

    'aup_url' => env('LEGAL_AUP_URL'),

    'aup_version' => env('LEGAL_AUP_VERSION'),

];
