<?php

declare(strict_types=1);

namespace Lynomia\Modules\SharedHosting\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Lynomia\Modules\SharedHosting\Domain\Enums\WordPressDomainSource;

/**
 * A name, where it comes from, and who administers the site.
 *
 * `domain_source` is required and has no default. A default would be a guess
 * about the slowest part of the order — whether the platform can make the name
 * point here in seconds or has to wait on another company — and the customer
 * is the only one who knows.
 *
 * There is no password field. The administrator's password is generated by the
 * platform, shown once, and never stored; a customer-chosen one submitted
 * through an API is a password in a request log.
 */
final class OrderWordPressSiteRequest extends FormRequest
{
    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'domain' => ['required', 'string', 'max:253'],
            'domain_source' => ['required', Rule::enum(WordPressDomainSource::class)],

            /*
             * Not "admin". WordPress installations with a user called `admin`
             * are the first thing every credential-stuffing run tries, and a
             * platform that defaulted to it would be creating that account for
             * every customer who did not think about it.
             */
            'admin_username' => ['required', 'string', 'min:3', 'max:60', 'not_in:admin,administrator,root'],
            'admin_email' => ['required', 'email:rfc', 'max:255'],

            'locale' => ['sometimes', 'string', 'max:12'],
        ];
    }
}
