<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        /*
         * Invoice numbers must be sequential, gapless and immutable. A database
         * sequence gives that under concurrency without an application lock, and
         * without the read-modify-write race that a MAX(number)+1 query has.
         */
        DB::statement('CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START WITH 1 INCREMENT BY 1');

        Schema::create('subscriptions', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('customer_id')->constrained('customers')->cascadeOnDelete();
            $table->foreignUlid('order_id')->nullable()->constrained('orders')->nullOnDelete();
            $table->foreignUlid('plan_id')->nullable()->constrained('plans')->nullOnDelete();

            $table->string('status', 32);            // active | past_due | suspended | cancelled | terminated
            $table->char('currency', 3);
            $table->string('billing_period', 16);

            $table->bigInteger('recurring_amount_minor');

            // The window the customer has currently paid for.
            $table->timestampTz('current_period_start');
            $table->timestampTz('current_period_end');

            // When the next invoice should be generated. Kept separate from
            // period_end so that invoicing can lead the period.
            $table->timestampTz('next_invoice_at')->nullable();

            $table->boolean('auto_renew')->default(true);
            $table->timestampTz('cancel_at')->nullable();
            $table->timestampTz('cancelled_at')->nullable();
            $table->timestampTz('ended_at')->nullable();

            // Dunning state.
            $table->unsignedSmallInteger('failed_payment_count')->default(0);
            $table->timestampTz('grace_period_ends_at')->nullable();
            $table->timestampTz('suspended_at')->nullable();

            $table->foreignUlid('coupon_id')->nullable()->constrained('coupons')->nullOnDelete();
            $table->unsignedSmallInteger('coupon_cycles_remaining')->nullable();

            $table->timestampsTz();

            $table->index(['customer_id', 'status']);
            // Drives the renewal worker: find everything due, cheaply.
            $table->index(['status', 'next_invoice_at']);
        });

        Schema::create('invoices', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('customer_id')->constrained('customers')->cascadeOnDelete();
            $table->foreignUlid('order_id')->nullable()->constrained('orders')->nullOnDelete();
            $table->foreignUlid('subscription_id')->nullable()->constrained('subscriptions')->nullOnDelete();

            // Immutable once issued. Allocated from invoice_number_seq.
            $table->string('number')->unique();

            $table->string('status', 24);            // draft | open | paid | void | uncollectible | refunded
            $table->char('currency', 3);

            $table->bigInteger('subtotal_minor')->default(0);
            $table->bigInteger('discount_minor')->default(0);
            $table->bigInteger('tax_minor')->default(0);
            $table->bigInteger('total_minor')->default(0);
            $table->bigInteger('amount_paid_minor')->default(0);
            $table->bigInteger('amount_refunded_minor')->default(0);
            // Generated by the database so it can never disagree with its parts.
            $table->bigInteger('amount_due_minor')
                ->storedAs('total_minor - amount_paid_minor + amount_refunded_minor');

            /*
             * The customer's billing details as they stood when the invoice was
             * issued. A later address change must not silently rewrite a
             * document that has already been sent and possibly filed for tax.
             */
            $table->jsonb('billing_snapshot');

            $table->timestampTz('issued_at')->nullable();
            $table->timestampTz('due_at')->nullable();
            $table->timestampTz('paid_at')->nullable();
            $table->timestampTz('voided_at')->nullable();

            $table->text('notes')->nullable();
            $table->timestampsTz();

            $table->index(['customer_id', 'status']);
            $table->index(['status', 'due_at']);
        });

        Schema::create('invoice_items', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('invoice_id')->constrained('invoices')->cascadeOnDelete();

            $table->string('kind', 32);              // plan | addon | usage | proration | credit | setup
            $table->string('description');
            $table->unsignedInteger('quantity')->default(1);

            $table->bigInteger('unit_amount_minor');
            $table->bigInteger('discount_minor')->default(0);
            $table->bigInteger('tax_minor')->default(0);
            $table->bigInteger('total_minor');

            $table->decimal('tax_rate', 9, 6)->default(0);
            $table->string('tax_name')->nullable();

            // The service period this line covers, for prorated and recurring
            // charges.
            $table->timestampTz('period_start')->nullable();
            $table->timestampTz('period_end')->nullable();

            $table->ulid('subscription_id')->nullable();
            $table->timestampsTz();

            $table->index('invoice_id');
        });

        Schema::create('wallets', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('customer_id')->constrained('customers')->cascadeOnDelete();
            $table->char('currency', 3);

            // Cached running total. The ledger below is the source of truth; a
            // scheduled check re-derives this and alerts on any divergence.
            $table->bigInteger('balance_minor')->default(0);

            $table->timestampsTz();

            // One wallet per customer per currency: balances are never mixed.
            $table->unique(['customer_id', 'currency']);
        });

        Schema::create('wallet_transactions', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('wallet_id')->constrained('wallets')->cascadeOnDelete();

            // Signed: positive credits the customer, negative debits them.
            $table->bigInteger('amount_minor');
            // Balance after this entry, so the ledger can be audited without
            // replaying every row.
            $table->bigInteger('balance_after_minor');

            $table->string('kind', 32);              // topup | refund | payment | adjustment | promotional
            $table->string('description');

            $table->ulid('invoice_id')->nullable();
            $table->ulid('transaction_id')->nullable();
            $table->foreignUlid('created_by_user_id')->nullable()->constrained('users')->nullOnDelete();

            $table->jsonb('metadata')->nullable();
            $table->timestampTz('created_at');

            $table->index(['wallet_id', 'created_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('wallet_transactions');
        Schema::dropIfExists('wallets');
        Schema::dropIfExists('invoice_items');
        Schema::dropIfExists('invoices');
        Schema::dropIfExists('subscriptions');

        DB::statement('DROP SEQUENCE IF EXISTS invoice_number_seq');
    }
};
