<?php

declare(strict_types=1);

namespace Lynomia\Modules\Billing\Infrastructure\Casts;

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use Illuminate\Database\Eloquent\Model;
use LogicException;

/**
 * A read-only cast for a column PostgreSQL computes for itself.
 *
 * Reading works normally; writing throws. The column is GENERATED ALWAYS AS
 * ... STORED, so an assignment would be rejected by the database anyway — but
 * it would be rejected at the moment the statement ran, which is typically
 * inside a settlement transaction at the end of a webhook. Failing at the
 * assignment instead names the mistake where it was made, and makes "the model
 * never writes this column" something the type system enforces rather than
 * something a comment asks for.
 *
 * @implements CastsAttributes<int|null, never>
 */
final class DatabaseGeneratedInteger implements CastsAttributes
{
    /**
     * @param  array<string, mixed>  $attributes
     */
    public function get(Model $model, string $key, mixed $value, array $attributes): ?int
    {
        return $value === null ? null : (int) $value;
    }

    /**
     * @param  array<string, mixed>  $attributes
     */
    public function set(Model $model, string $key, mixed $value, array $attributes): never
    {
        throw new LogicException(sprintf(
            'Attribute [%s] on [%s] is generated by the database and cannot be assigned. '
            .'Change the columns it is derived from instead.',
            $key,
            $model::class,
        ));
    }
}
